# Generated by Django 2.2.5 on 2019-10-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191007_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='opened',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
